### ISSUE TITLE
ObjectDisposedException thrown at endpoint shutdown

### ISSUE THREAD

**Issue by noctovis** [Particular/ServiceControl.Plugin.Nsb5.Heartbeat#17] opened 2017-02-08 15:20 UTC
### Symptoms

- `System.ObjectDisposedException` thrown by the heartbeats feature when the endpoint is shut down. 

### Who's affected

All customers using the Heartbeat plugin

### Analysis

In V5 there isn't a clean way to handle shutdown of the endpoint that works for Send Only as well as Full Duplex. The implementation relies on the fact that the NServiceBus container is disposed of which causes the heartbeats timer to get disposed. Unfortunately this only happens after the transport has been shut down. This leads to cases where the heartbeat plugin is trying to send a message through a transport that has been shut down and the exception is thrown.

### Fix

As there isn't a clean abstraction to shut down cleanly, the decision was made to catch the exception  and log it at the `Debug` level.

---

We've been seeing exceptions pouring in from the heartbeat package.
We log these in Stackify and have seen up to 3000 occurrences.
We're running our endpoints within Azure Webjobs. Please let me know if you need any more info, here's the stacktrace:
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'CommonObjectBuilder'.
at NServiceBus.ObjectBuilder.Common.CommonObjectBuilder.ThrowIfDisposed() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Obsoletes.cs
at NServiceBus.ObjectBuilder.Common.CommonObjectBuilder.Build(System.Type) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\ObjectBuilder\Common\CommonObjectBuilder.cs
at NServiceBus.Azure.Transports.WindowsAzureServiceBus.QueueAndTopicByEndpoint.QueueAndTopicByEndpointTopology.GetSender(NServiceBus.Address) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Topology\QueueAndTopicByEndpoint\QueueAndTopicByEndpointTopology.cs:line 111
at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusSender.SendInternal(NServiceBus.TransportMessage, NServiceBus.Unicast.SendOptions, Boolean) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\AzureServiceBusSender.cs:line 37
at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusSender.Send(NServiceBus.TransportMessage, NServiceBus.Unicast.SendOptions) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\AzureServiceBusSender.cs:line 22
at ServiceControl.Plugin.ServiceControlBackend.Send(System.Object, System.TimeSpan) in C:\Build\src\ServiceControl.Plugin.Nsb5.Heartbeat\ServiceControlBackend.cs:line 51
at ServiceControl.Plugin.Nsb5.Heartbeat.Heartbeats.SendHeartbeatMessage(NServiceBus.Hosting.HostInformation) in C:\Build\src\ServiceControl.Plugin.Nsb5.Heartbeat\Heartbeats.cs:line 118
at ServiceControl.Plugin.Nsb5.Heartbeat.Heartbeats+<>c__DisplayClass5_0.<StartHeartbeats>b__0(System.Object) in C:\Build\src\ServiceControl.Plugin.Nsb5.Heartbeat\Heartbeats.cs:line 79
at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.TimerQueueTimer.CallCallback()
at System.Threading.TimerQueueTimer.Fire()
at System.Threading.TimerQueue.FireQueuedTimerCompletion(System.Object)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by SeanFeldman** [comment] 2017-02-09 00:03
It looks like 2 possible things could be involved:
1. There's a bug with the heartbeat plugin when endpoint is shutting down.
1. The 3000 exceptions are related, but they shouldn't occur if your webjob is a `Continuous` webjob.

In order to run an endpoint in a webjob, these are the conditions that need to be fulfilled:
1. The webjob has to be a `Continuous` wejob
1. Webapp has to have `AlwaysOn` turned on. 
1. AppService plan has to be a [dedicated AppService plan](https://github.com/Azure/Azure-Functions/wiki/Enable-Always-On-when-running-on-dedicated-App-Service-Plan) (from Basic plan and up). 

In case either of this requirements is not fulfilled, the webjob will stop, causing endpoint to shutdown.

@Particular/servicecontrol-maintainers could you please look at the shutdown exception with the plugin?

**Comment by gbiellem** [comment] 2017-02-09 00:22
Thanks @SeanFeldman   - yep will try and repro

**Comment by noctovis** [comment] 2017-02-09 06:46
@SeanFeldman Thanks Sean for the info, I double checked my appservices, and they all correspond to the requirements you ask for:
- they're all continuous webjobs
- the appservices have the setting always on turned on
- they all run on dedicated appservice plan's (basic and up)

So I'm thinking there must be something else going on. It is good to know though that these settings might cause these exceptions, so thanks!

**Comment by gbiellem** [comment] 2017-02-12 01:29
@noctovis 

 I'm going to need more info to track this down as I've not been able to reproduce the System.ObjectDisposedException you are experiencing. 

I've made a simple WebJob hosting an NSB 5 endpoint and added the heartbeat plugin and it operates normally.

Regarding the 3000 entries. If the webjob criticially failed  Azure would try and restarted it. So i'm guessing the job was stuck in a restart loop of start up->boom->report-to-stackify
I got into a loop like this trying to reproduce your issue.

Can you provide we with versions of the packages your using and a  sample of how your initialising your endpoints? This may help me identify the issue

**Comment by noctovis** [comment] 2017-02-21 14:19
Hi @gbiellem, 

I'm sorry for the delay. Here's an example of how we set up our endpoints:

`            var configuration = new BusConfiguration();

            // Set Servicecontrol appsettings
            AppSettingsManager.CreateOrUpdateAppSettingAndRefresh(
                ServiceControlSettings.ServiceControlQueue,
                environmentSettings.ServiceControlQueue);
            AppSettingsManager.CreateOrUpdateAppSettingAndRefresh(
                ServiceControlSettings.HeartbeatInterval,
                environmentSettings.ServiceControlHeartbeatInterval);

            // Set displayname in ServicePulse to support scaled out endpoints
            string websiteInstanceId = Environment.GetEnvironmentVariable("WEBSITE_INSTANCE_ID");
            var displayName = string.Concat(assemblyName, "_OnInstance_", websiteInstanceId);
            configuration.GetSettings().Set(NServicebusHostInformationDisplayNameSetting, displayName);

            // Bus configuration settings
            // This sets conventions for unobstrusive mode
            Conventions.Configure(configuration);
            configuration.EndpointName(assemblyName);
            configuration.License(environmentSettings.NServiceBusLicense);
            configuration.UseContainer<UnityBuilder>(
                c => c.UseExistingContainer(new DocumentsEndpointCatalog().Factory.GetContainer()));

            NServiceBus.Logging.LogManager.UseFactory(new Virteo.Common.NServiceBus.Logging.NServiceBusToStackifyLoggerFactory());

            // Set transport
            configuration.UseTransport<AzureServiceBusTransport>()
                    .ConnectionString(ServiceBusConnectionStringHelper.GetConnectionString());

            // Set transport transaction settings - 
            var transactionSettings = configuration.Transactions();
            transactionSettings.DisableDistributedTransactions();
            transactionSettings.WrapHandlersExecutionInATransactionScope();

            // Persistence
            var nhConfiguration = new NHibernateConfiguration
            {
                Properties =
                                      {
                                          {
                                              "connection.driver_class",
                                              "NHibernate.SqlAzure.SqlAzureClientDriver, NHibernate.SqlAzure"
                                          },
                                          {
                                              "connection.connection_string",
                                              environmentSettings.NsbSqlPersistenceConnectionString
                                          },
                                          {"dialect", "NHibernate.Dialect.MsSql2012Dialect"}
                                      }
            };
            var persistence = configuration.UsePersistence<NHibernatePersistence>();
            persistence.UseConfiguration(nhConfiguration);

            // Databus
            var dataBusExtentions = configuration.UseDataBus<AzureDataBus>();
            dataBusExtentions.ConnectionString(environmentSettings.StorageConnectionString);

            configuration.ScaleOut().UseSingleBrokerQueue();

            // Start the bus
            var startableBus = Bus.Create(configuration);
            startableBus.Start();

            while (!cancellationToken.IsCancellationRequested)
            {
                Thread.Sleep(1000);
            }

            startableBus.Dispose();`

Let me know if you have more questions!

**Comment by SimonCropp** [comment] 2017-02-21 19:10
@noctovis on a side note I see you use some NSB classes prior to configuring logging. This will result in some classes using the default NSB logging and some using your custom logging. You should move your LogManager.UseFactory up prior to using the other NSB classes. https://docs.particular.net/nservicebus/logging/#when-to-configure-logging

**Comment by SimonCropp** [comment] 2017-02-21 19:24
@noctovis what method are you using to host NSB?

**Comment by noctovis** [comment] 2017-02-21 19:45
@simoncropp noted, thanks!
We're hosting them in azure webjobs, like sean described on his blog.

**Comment by SeanFeldman** [comment] 2017-02-21 21:08
@noctovis quick note about the hosting part (waiting until cancellation token is cancelled). The signature of the method is missing, but you can host your webjob in a `Task` based method and replace `Thread.Sleep()` with `Task.Delay()` which is a better option.

In the [Azure show case](https://docs.particular.net/samples/show-case/cloud-azure/) we do [exactly that](https://github.com/Particular/docs.particular.net/blob/master/samples/show-case/cloud-azure/Core_6/Store.Sales/Program.cs#L35).

**Comment by noctovis** [comment] 2017-02-21 21:49
Noted! Thanks Sean!

**Comment by noctovis** [comment] 2017-02-28 08:52
@SimonCropp Any news regarding this issue?

**Comment by mikeminutillo** [comment] 2017-03-01 07:19
I haven't been able to reproduce it but I think that there is a race condition when we dispose of the heartbeats timer [here](https://github.com/Particular/ServiceControl.Plugin.Nsb5.Heartbeat/blob/master/src/ServiceControl.Plugin.Nsb5.Heartbeat/Heartbeats.cs#L52).

What I think is happening is:
1. The timer queues the heartbeat callback in the threadpool
2. The call to dispose the endpoint happens
3. That call trickles down to the heartbeats plugin which calls dispose on the timer
4. The call to dispose (from 2) completes which shuts down the endpoint
5. The callback from 1 reaches the threadpool and gets executed but there's no transport to send heartbeat messages through.

There's [an overload](https://msdn.microsoft.com/en-us/library/b97tkt95(v=vs.110).aspx) of `Timer.Dispose()` which will allow us to monitor the shutdown of the timer and wait for all callbacks to complete. 

We have [other examples of following this pattern in ServiceControl](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/RavenDB/Expiration/ExpiredDocumentsCleanerBundle.cs#L49)

**Comment by mikeminutillo** [comment] 2017-03-01 07:47
Actually it's worse than that!

The Heartbeats code is inside a class that implements both `IWantToRunWhenConfigurationIsComplete` and `IDisposable`. `IWantToRunWhenConfigurationIsComplete` sets up the `System.Threading.Timer` to fire every heartbeat interval and `IDisposable` stops it. 

The thing is, we never explicitly call that `Dispose()`. It happens when the container is disposed. The container is disposed only AFTER the endpoint has been shut down ([here](https://github.com/Particular/NServiceBus/blob/support-5.2/src/NServiceBus.Core/Unicast/UnicastBus.cs#L748)). 

This all changed when we switched heartbeats from being a Feature because features were not activated for SendOnly endpoints ([here](https://github.com/Particular/ServiceControl.Plugin.Nsb5.Heartbeat/commit/81641aa9170a07e95e2fee0c69c86ffb75431b6c#diff-d5a8d2009c2555df56e3244f072bbd14R15)).

To fix this, we can either catch the exception and ignore it (as it's expected) or we need to find a better hook to shut down the heartbeats monitor. I wonder if we shouldn't go back to being a proper feature and then provide a separate API for SendOnly endpoints to use.

**Comment by SzymonPobiega** [comment] 2017-03-08 09:47
Closing as #19 has been merged.

**Closed by SzymonPobiega** 2017-03-08 09:47 UTC
Labels: State: In Progress, Type: Bug

**Comment by mikeminutillo** [comment] 2017-03-09 03:20
@noctovis when you get a chance can you please update your endpoints to 3.0.1 of the heartbeats plugin and see if it resolves the issue your originally raised?

**Comment by noctovis** [comment] 2017-03-09 06:46
@mikeminutillo I will, thanks guys!
